# Generated by Django 5.1.4 on 2024-12-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Principle'), (2, 'Teacher'), (3, 'Student'), (4, 'Parent')], default=0),
            preserve_default=False,
        ),
    ]
