# Generated by Django 5.1.4 on 2024-12-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0002_user_user_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField(default='1980-01-01', max_length=8)),
                ('tel', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('child', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField(default='1980-01-01', max_length=8)),
                ('tel', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('subjects', models.CharField(max_length=300)),
                ('current_class', models.CharField(max_length=300)),
                ('activities', models.CharField(max_length=300)),
                ('parent_1', models.CharField(max_length=300)),
                ('parent_2', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField(default='1980-01-01', max_length=8)),
                ('tel', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('subjects', models.CharField(max_length=300)),
                ('classes', models.CharField(max_length=300)),
            ],
        ),
    ]
