# Generated by Django 5.1.4 on 2024-12-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0006_alter_teacher_classes_alter_teacher_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(default='', to='grade_app.classes', verbose_name='Classes'),
        ),
    ]
