# Generated by Django 5.1.4 on 2024-12-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0008_teacher_last_login_teacher_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='parent',
            name='password',
            field=models.CharField(default=0, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
