# Generated by Django 5.1.4 on 2024-12-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0009_parent_last_login_parent_password_student_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Principle'), (2, 'Teacher'), (3, 'Student'), (4, 'Parent')], default=0),
        ),
    ]
