# Generated by Django 5.1.4 on 2024-12-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0010_alter_user_user_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'parent', 'verbose_name_plural': 'parents'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(to='grade_app.classes', verbose_name='Classes'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tel',
            field=models.CharField(max_length=12, verbose_name='telephone number'),
        ),
    ]
