# Generated by Django 5.1.4 on 2024-12-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0011_alter_parent_options_alter_teacher_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(default='', to='grade_app.classes', verbose_name='Classes'),
        ),
    ]
