# Generated by Django 5.1.4 on 2024-12-25 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0012_alter_teacher_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(to='grade_app.classes', verbose_name='Classes'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade_app.subjects', verbose_name='Subjecs'),
        ),
    ]
