# Generated by Django 5.1.4 on 2024-12-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0013_alter_teacher_classes_alter_teacher_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(default='01-01-1990', max_length=8),
        ),
    ]
