# Generated by Django 5.1.4 on 2025-01-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0025_delete_activities_user_classes_user_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='tel',
        ),
    ]
