# Generated by Django 5.1.4 on 2025-01-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0026_remove_parent_date_of_birth_remove_parent_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='sbuject_short',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
