# Generated by Django 5.1.4 on 2025-01-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0028_rename_sbuject_short_subjects_subject_short_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
    ]
