# Generated by Django 5.1.4 on 2025-01-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0029_remove_user_classes_remove_user_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(default='', to='grade_app.subjects', verbose_name='Subjecs '),
        ),
    ]
