# Generated by Django 5.1.4 on 2025-01-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0030_alter_teacher_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ManyToManyField(default='', to='grade_app.classes', verbose_name='Classes'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(default='', to='grade_app.subjects', verbose_name='Subjecs '),
        ),
    ]
