# Generated by Django 5.1.4 on 2025-01-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0031_remove_student_current_class_remove_student_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='main_class',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
