# Generated by Django 5.1.4 on 2025-03-26 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0032_teacher_main_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=300)),
                ('school_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grade_app.classes')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grade_app.student')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grade_app.subjects')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
            },
        ),
    ]
