# Generated by Django 5.1.4 on 2025-03-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0033_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='school_class',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='grades',
            name='student',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='grades',
            name='subject',
            field=models.CharField(max_length=70),
        ),
    ]
