# Generated by Django 5.1.4 on 2025-04-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0034_grades_grade_alter_grades_school_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.CharField(default='', max_length=300),
        ),
    ]
