# Generated by Django 5.1.4 on 2025-04-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0035_remove_student_current_class_remove_student_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='main_class',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(default='', max_length=300),
        ),
    ]
