# Generated by Django 5.1.4 on 2025-04-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0036_remove_teacher_classes_alter_teacher_main_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='main_class',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
